sudo: false  # To use travis container infrastructure

language: python

python:
  - "2.7"

script:
  - pip install .

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: develop
